---
apiVersion: v1
kind: Pod
metadata: 
  name: openmrs
  labels:
    app: openmrs
    ver: "1.0"
spec:
  containers:
    - name: openmrs
      image: munna033/openmrs:1.0
      ports:
        - containerPort: 8080
          protocol: TCP