---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
  labels:
    app: openmrs
  annotations:
    kubernetes.io/change-cause: "version 1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
        version: v1.0
    spec:
      containers:
        - image: openmrs/openmrs-reference-application-distro:latest
          name: openmrs
          ports:
            - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  name: openmrs-svc
  labels:
    job: lb
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: openmrs
  type: LoadBalancer